# Generated by Django 3.1.3 on 2022-01-23 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(default=False, max_length=24)),
                ('subject', models.CharField(default=False, max_length=200)),
                ('content', models.TextField()),
                ('image', models.TextField(null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
